task: mbpp_sanitized_llada1.5
dataset_path: json
dataset_name: null
dataset_kwargs:
  # data_files: https://huggingface.co/datasets/Muennighoff/mbpp/resolve/main/data/sanitized-mbpp.json
  data_files: /mnt/dllm/dulun.dl/dllm_decoding/sanitized-mbpp.json
process_docs: !function utils.process_docs
test_split: train
output_type: generate_until
unsafe_code: true
doc_to_text: "You are an expert Python programmer, and here is your task: {{text}} Your code should pass these tests:\n\n{{test_list_str}}\n\nPlease enclose your code within delimiters as follows:\n```python\n# YOUR CODE HERE\n```\n\n"
doc_to_target: "{{test_list_str}}"
num_fewshot: 0
metric_list:
  - metric: !function utils.pass_at_1
    aggregation: mean
    higher_is_better: true
generation_kwargs:
  until:
    - "\n```\n"
  max_gen_toks: 8192
  temperature: 0.0
  do_sample: false
metadata:
  version: 1.0
